az-digital/az-quickstart-scaffolding

composer.json
Fixes #11.  Applied fix from drupal-check PR to fix TTY issue so we can use latest drupal-check version that isn't affected by the PHPStan "class not found" errors.
=> Fixes #11: Use latest drupal-check release with patch for TTY issue.

composer.json
Recently it was noticed that there was a CPU utilization issue where running the Drupal console would execute an infinite loop and never actually run. This seems to have likely happened when we pinned drupal/console from `^1.0.2` to `1.0.2`. It turned out that `1.0.2` was actually fairly old and it'd been relying on the `^` to bring in a fix for an infinite loop in finding translations. This pull request brings in the version where the issue was addressed.
**Testing:**
Verify that the drupal console is able to run without extreme CPU utilization.
```
~/example$ lando start
(snipped)
~/example$ lando drupal
Drupal Console version 1.9.3
Usage:
command [options] [arguments]
Options:
-h, --help             Display this help message
-q, --quiet            Do not output any message
-V, …
```
=> Fixes #13: Using the Drupal console causes high CPU usage/timeout issues.

composer.json
Changes version constraints for Drupal core dependencies to be non-specific so versions can be set by profile repo.
az-digital/az_quickstart#33
az-digital/az_quickstart#56
=> Allow Drupal core dependency versions to be set by profile (az-digital/az_quickstart#33, az-digital/az_quickstart#56)

.lando.yml, .probo.yaml, composer.json, scripts/composer/ScriptHandler.php
Backwards compatible changes from #21 
- Updates lando, probo configs to be more like profile repo configs and ready for D9
- Updates zaporylie/composer-drupal-optimizations 
- Updates copy of drupal-composer/drupal-project composer script file with latest changes (removes deprecated constant error for D9)
=> az-digital/az_quickstart#220: Backwards-compatible D9 scaffold repo changes.

.probo.yaml, composer.json
Still need to update drupal-console-extend-plugin once this is merged https://github.com/hechoendrupal/drupal-console-extend-plugin/pull/25/files
=> WIP Update composer scaffolding repo with specific package version numbers that are compatible with composer 2.0

composer.json
**Describe the bug**
After adding in our local fork of `pheromone/phpcs-security-audit` located [here](https://github.com/az-digital/phpcs-security-audit) composer builds in lando are occasionally throwing API rate warnings:
```
GitHub API limit (0 calls/hr) is exhausted, could not fetch https://api.github.com/repos/az-digital/phpcs-security-audit/tags?per_page=100. Create a GitHub OAuth token to go over the API rate limit. You can also wait until ? for the rate limit to reset.
```
**Related Issue**
#28 
**To Test**
1. Test locally
2. Perform local lando builds
3. May take several repetitions, as it's time-limited.
4. Verify that the above error does not occur
=> Fixes #28 Fix API rate limit on forked repository

.ddev/commands/web/quickstart-branch, .lando.yml, .probo.yaml, quickstart_branch.sh
Similar to changes we just made to the probo, lando, and ddev config files in the 2.0.x branch of the profile repo.
=> Updated 'main' references to '2.0.x'.

.ddev/commands/web/quickstart-branch, quickstart_branch.sh
From composer documentation:
>In the case of a branch with a version-like name (v1, in this case), you append -dev as a suffix, rather than using dev- as a prefix.
https://getcomposer.org/doc/articles/versions.md#branches
These same changes are also included in #33 for the `2.0.x` branch but it occurred to me that it would probably be best to include these specific changes in both branches.
=> Updated quickstart-branch scripts to handle strange composer rules for dev prefix/suffix on branch names.

composer.json
Updated Drush version to fix Drupal 9.1.x compatibility issue (https://github.com/drush-ops/drush/issues/4580)
=> Update drush to 10.3.6 to address Drupal 9.1.x compatibility issue.

composer.json
This pull request is a matching pull request for https://github.com/az-digital/az_quickstart/pull/561 and adds [Asset Packagist](https://asset-packagist.org/) to the list of scaffolding repositories, as well as `composer/installers` settings for npm and bower assets. This is intended to provide a way to add third-party client side libraries to Quickstart.
Related issue: #40
=> Fixes #40 Third Party Libraries Support

composer.json
We tried adding this alias to `az-quickstart-dev` but that didn't work because inline aliases are only supported in root level composer files.
=> Fixes az-digital/az-quickstart#699: Add temporary inline require alias for composer security update.

composer.json
az-quickstart-scaffolding/composer.json
Lines 29 to 30 in c3f179b
"php": ">=7.0", 
"az-digital/az_quickstart": "~2.1", 
I could be wrong about all of this.
Because we are using the ~ operator in our composer.json for our az-digital/az_quickstart version constraint, the allowed range of installable versions is >=2.1.0 <3.0.0
This means that the earliest tagged version of quickstart that is possible to use with the latest scaffolding repo is 2.1.0-alpha1 which has a core version requirement pinned at "drupal/core-recommended": "9.0.8", and the minimum php version allowed in drupal 9.0.8 is 7.3
https://getcomposer.org/doc/articles/versions.md#tilde-version-range-
It seems as though we may be using an undocumented feature of composer where if you use a tilde and a version number that hasn't …
=> Closes #46 Update minimum PHP version.

.lando.yml
On current versions of lando that are using composer 2.0, an attempt to use the Scaffolding's lando file fails with a build step error because Hirak/Prestissimo is not compatible with the 2.0 series of the composer-plugin-api. (and has subsequently been abandoned.)
I think this escaped notice since we don't do Lando builds of the scaffolding very often.
Ensure the following build step failure doesn't happen:
```
Changed current directory to /var/www/.composer
[InvalidArgumentException]                                                                                                                 
Package hirak/prestissimo at version ^0.3.9 has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version 
```
=> Fixes #48 remove Hirak/Prestissimo.

composer.json
Updating scaffolding repo to use updated Quickstart branch alias for `dev-main` (see az-digital/az_quickstart#1264)
=> Update composer.json to use new Quickstart dev-main branch alias.

composer.json
This should not be merged until _after_ the `2.2.x` branch is created in this repo.
=> az-digital/az_quickstart#1367: Update composer.json to use new Quickstart dev-main branch alias.

.lando.yml, .probo.yaml, quickstart_branch.sh
2.2.x branch specific changes needed for CI and local development tool configs. 
The destination branch for this PR should be changed to the 2.2.x branch once it is created. This should only be merged into the 2.2.x branch.
=> az-digital/az_quickstart#1367: 2.2.x branch-specific changes for CI configs.

composer.json
See az-digital/az_quickstart#1491
=> az-digital/az_quickstart#1491: Temporarily remove assset-packagist as composer repo.

composer.json
This reverts commit 39d4545d7541e59438d0bd782ada84c95fcd41c1.
=> Revert "Prerequisite to address az-digital/az_quickstart#1491: Tempor…arily remove assset-packagist as composer repo. (#60)"

.probo.yaml, composer.json
See [getcomposer.org/doc/06-config.md#allow-plugins](https://getcomposer.org/doc/06-config.md#allow-plugins)
=> Closes #64 Prepare for composer version 2.2.0 upgrade where we need to explicitly allow plugins to run.

.github/dependabot.yml
Would be good to have dependabot generate PRs for this project's dependencies as well.
=> Enable dependabot PRs for scaffolding repo pinned dependencies.

.ddev/config.yaml
Closes #66
APIVersion removal per https://github.com/drud/ddev/issues/2116
Tested locally with WSL2.
=> Closes #66: Increments MariaDB version, Drupal version, removes API version

composer.json
Update the [az-digital/az_quickstart composer.json requirement](https://github.com/az-digital/az-quickstart-scaffolding/blob/main/composer.json#L30) in the main branch of the az-digital/az_quickstart_scaffolding repo to use new Quickstart dev-main branch alias (~2.5).
=> az-digital/az_quickstart#1703 2.4.x release preparations

composer.json
Updates 2.3.x branch with recent changes merged to main.
This change is particularly important because Quickstart 2.3.x PRs are broken without it:
- #79 
We may not want to squash merge this one since I cherry-picked the commits from main.
=> Closes #85: Backport recent changes into 2.3.x branch.

.ddev/config.yaml, .lando.yml, .probo.yaml, composer.json
Scaffolding repo changes needed for https://github.com/az-digital/az_quickstart/issues/2081
=> az-digital/az_quickstart#2081: Make scaffolding repo D10 compatible.

README.md
Update out of date version number in order to avoid sending people down the wrong path right from the start.
=> Update recommended version to 2.7.x

.probo.yaml, composer.json
Companion PR for https://github.com/az-digital/az_quickstart/pull/2587
- Upgrades Drush to version 12
- Sets Quickstart requirement to ~2.8 for main branch (this probably should have been changed when we created the 2.7.x release branch)
- Updates probo config so that drush launcher used by Probo can find Drush 12
=> Upgrade Drush for az-digital/az_quickstart#2573

.github/workflows/prepare-for-minor-release.yml
It seems that the repo is only cloned and changed directory into in the actions/checkout step.
Remove unneeded step
Remove push existing branch step
=> Closes #124 fix order of setup steps, and some code quality and redundancy updates in prepare repo for minor release workflow.

composer.json
Should prevent future PHP errors triggered by composer scripts due to mismatched `drupal/core-composer-scaffold` and `drupal/core-recommended` versions.
=> #137: Pin drupal/core-composer-scaffold to ^10.2 for main (and forthcoming 2.9.x).

.probo.yaml, composer.json
Should prevent future PHP errors triggered by composer scripts due to mismatched `drupal/core-composer-scaffold` and `drupal/core-recommended` versions.
Also updates Probo config to work with numeric profile repo branch names (e.g. `2.8.x`).
=> #137: Pin drupal/core-composer-scaffold to ^10.1 for 2.8.x.

composer.json
Should prevent future PHP errors triggered by composer scripts due to mismatched `drupal/core-composer-scaffold` and `drupal/core-recommended` versions.
=> #137: Pin drupal/core-composer-scaffold to ^10.0 for 2.7.x.

.github/workflows/prepare-for-minor-release.yml
In this pull request, i change the branch name convention for new branches in the scaffolding repo to start with a letter instead of a number, which should conflict less with our build tools and branch restrictions.
=> Close #150 Update branch name convention in github action.

composer.json
Pinning to a specific webflo/drupal-finder release is causing compatibility problems with different versions of Drupal core and the Upgrade status module included in our dev dependencies metapackage (see https://github.com/az-digital/az-quickstart-dev/actions/runs/9307170462/job/25801308691?pr=110).  We should make the version constraint more flexible.
Should be backported to 2.10.x, 2.9.x at least.
=> Relax webflo/drupal-finder requirement

composer.json
Changes needed for upgrading Drupal core to 10.3.x.
=> az-digital/az_quickstart#3290: Prepare scaffolding repo for Drupal 10.3.x.

composer.json
In https://github.com/az-digital/az-quickstart-dev/pull/111 we're planning to replace drupal/core-dev-pinned with drupal/core-dev so we need to add a core minor version constraint here to ensure the correct version of drupal/core-dev is used with this branch.
We'll need to re-run the automated Probo checks for this PR after https://github.com/az-digital/az-quickstart-dev/pull/111 is merged.
=> az-digital/az_quickstart#3290: Make 2.9.x branch compatible with switch to drupal/core-dev.

.probo.yaml, composer.json
In az-digital/az-quickstart-dev#111 we're planning to replace `drupal/core-dev-pinned` with `drupal/core-dev` so we need to add a core minor version constraint here to ensure the correct version of `drupal/core-dev` is used with this branch.
=> az-digital/az_quickstart#3290: Make 2.10.x branch compatible with switch to drupal/core-dev + fix broken Probo config in 2.10.x branch.

composer.json
Should fix az-digital/az_quickstart#3581
Originated with #155.
We should have used ~`^10.2.0`~ `~10.2.0` as our constraint instead of `^10.2`.  🤦🏻‍♂️
=> az-digital/az_quickstart#3581: Fix drupal/core-dev constraint in 2.10.x branch.

composer.json
Should fix az-digital/az_quickstart#3581
Originated with #155.
We should have used `~10.2.0` as our constraint instead of `^10.2`.  🤦🏻‍♂️
=> az-digital/az_quickstart#3581: Fix drupal/core-dev constraint in 2.9.x branch.

composer.json
Forgot to also fix `drupal/core-composer-scaffold` constraint.
=> az-digital/az_quickstart#3581: Fix drupal/core-composer-scaffold constraint in 2.10.x branch.

composer.json
Should prevent az-digital/az_quickstart#3581 from happening again when Drupal 10.4.0 comes out.
Originated with #155.
We should have used `~10.3.0` as our constraint instead of `^10.3`.  🤦🏻‍♂️
=> az-digital/az_quickstart#3581: Fix drupal/core-scaffold and drupal/core-dev constraints in 2.11.x branch.

composer.json
Should prevent az-digital/az_quickstart#3581 from happening again when Drupal 10.4.0 comes out.
Originated with #155.
We should have used `~10.3.0` as our constraint instead of `^10.3`.  🤦🏻‍♂️
=> az-digital/az_quickstart#3581: Fix drupal/core-scaffold and drupal/core-dev constraints in main branch.

composer.json
We already upgraded the main branch of the az_quickstart repo to 10.4.x but haven't yet updated this scaffolding repo.
=> az-digital/az_quickstart#3934: Scaffolding repo changes for Drupal 10.4.x.

composer.json
(cherry picked from commit 0e066eb88c0db549c8e8805dcef0225ead6ead86)
2.x back-port of #200 for az-digital/az_quickstart#4426
=> az-digital/az_quickstart#4426: Scaffolding repo updates for Drupal 10.5 (2.x back-port of #200)

composer.json
Looks like we missed a step when updating the Quickstart repos during/after creating the `2.14.x` release branches.
This repo's main branch should have been updated to use `~3.0` as the version requirement for `az-digital/az_quickstart`.  Not sure how we missed this.  We updated the `az-digital/az-quickstart-dev` constraint in #202 but forgot to update the `az-digital/az_quickstart` constraint, I guess.
Currently the `2.x` branch requires a newer version of Quickstart than `main` 😬 :
https://github.com/az-digital/az-quickstart-scaffolding/blob/2.x/composer.json#L30
https://github.com/az-digital/az-quickstart-scaffolding/blob/main/composer.json#L25
=> az-digital/az_quickstart#4446: Update az_quickstart requirement for main branch to ~3.0.
