composer.json
=> Fixes #17: Updated drupal-check, removed patch.

composer.json
=> #504: Removed security check composer script.

.ddev/config.yaml, .lando.yml, .probo.yaml
Scaffolding repo changes for az-digital/az_quickstart#350.
=> #350: Updated PHP versions to 7.4.

README.md
Mostly copied from the slides for the developer workshop presentation.  We should probably refine/add a lot more than this eventually but I think it'd be good to get something added ASAP.
=> Closes #50: Added basic README content.

.lando.yml, .probo.yaml, quickstart_branch.sh
2.1.x branch specific changes needed for CI and local development tool configs.  This should only be merged into the `2.1.x` branch.
=> 2.1.x branch-specific changes for CI configs.

.lando.yml
Updated migrate_d7_public_path to use migrate_files.
Closes az-digital/az_quickstart#1441
=> Closes az-digital/az_quickstart#1441 Updated migrate_d7_public_path

composer.json
Step 3 to prepare for 2.3.0 minor release:
https://github.com/az-digital/az_quickstart/wiki/Steps-to-create-minor-release
=> az-digital/az_quickstart#1561: Update composer.json to use new Quickstart dev-main branch alias.

.lando.yml, .probo.yaml, quickstart_branch.sh
Step 5 to prepare for 2.3.0 minor release
https://github.com/az-digital/az_quickstart/wiki/Steps-to-create-minor-release
=> az-digital/az_quickstart#1561: 2.3.x branch-specific changes for CI configs.

README.md
=> #77 2.2.x branch-specific changes for composer command.

README.md, composer.json
Step 3 from https://github.com/az-digital/az_quickstart/wiki/Steps-to-create-a-minor-release
=> Prepare scaffolding main branch for 2.5.0 pre-release.

.lando.yml, .probo.yaml, quickstart_branch.sh
Step 5 from https://github.com/az-digital/az_quickstart/wiki/Steps-to-create-a-minor-release
=> Update fallback branch references in CI & local dev tools for 2.5.x branch.

README.md
I missed updating one of the 2.4.x references in the README.
=> Update missed 2.4.x reference in README.

.ddev/commands/web/quickstart-install
Minor drush additions/changes to DDEV in scaffolding to align with az_quickstart's DDEV install command.
Tested locally on DDEV.
=> Closes #98 Added DDEV CAS disabling, cache rebuild, standard pw

composer.json
Step 3 from https://github.com/az-digital/az_quickstart/wiki/Steps-to-create-a-minor-release
=> Prepare scaffolding main branch for 2.7.0 pre-release.

.lando.yml, .probo.yaml, quickstart_branch.sh
Step 5 from https://github.com/az-digital/az_quickstart/wiki/Steps-to-create-a-minor-release
=> 2.7.x default branch changes

scripts/composer/ScriptHandler.php
Closes #131 
https://www.drupal.org/node/3244583
=> Closes #131 Address deprecation in QuickstartProject\composer\ScriptHandler::createRequiredFiles().

composer.json, scripts/composer/ScriptHandler.php
=> Closes #130 Replace usage of abandoned webmozart/path-util package

.ddev/commands/web/quickstart-install, .lando.yml, .probo.yaml
=> az-digital/az_quickstart#3223: Update test account passwords.

.ddev/commands/web/quickstart-install, .lando.yml, .probo.yaml
Closes #186
Update 2024 passwords
=> Closes #186: Update local dev and ProboCI test user account passwords for 2025

.github/workflows/prepare-for-minor-release.yml
Adds changes to scaffolding repo workflow that correspond with changes made in main profile repo in https://github.com/az-digital/az_quickstart/pull/4593
=> az-digital/az_quickstart#4592: Update prepare-for-minor-release workflow to support dynamic source branch.

.github/workflows/prepare-for-minor-release.yml
(cherry picked from commit 16e3c8b15a462cbf3104c26909743de2d5a08c5c)
2.x back-port of #211 for az-digital/az_quickstart#4592
=> az-digital/az_quickstart#4592: Update prepare-for-minor-release workflow to support dynamic source branch. (2.x back-port of #211)
